name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

concurrency:
    group: ${{ github.workflow }}-${{ github.ref_name }}
    cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: cargo build --release

    - name: Lint
      run: cargo clippy --all-features -D warnings

    - name: Run tests
      run: |-
        cargo test
        cargo test --no-default-features --test lib_test
        cargo test --features resilience
        cargo test --features async
        cargo test --all-features

