name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

concurrency:
    group: ${{ github.workflow }}-${{ github.ref_name }}
    cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: cargo build --release

    - name: Lint
      run: cargo clippy --all-features --all-targets -- -Dwarnings

    - name: Run tests
      shell: pwsh
      run: |-
        ps
        Start-Process -NoNewWindow -FilePath "pwsh.exe" -ArgumentList "-Command","Start-Sleep","-Seconds","300"
        echo "after"
        ps
        cargo test -- --test-threads=1
        cargo test --no-default-features --test lib_test -- --test-threads=1
        cargo test --features resilience -- --test-threads=1
        cargo test --features async -- --test-threads=1
        cargo test --all-features -- --test-threads=1

